# Generated by Django 3.1.7 on 2021-05-13 10:31

import asha_web_ja.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_image', verbose_name='Blog Image')),
                ('blog_large_image', models.ImageField(blank=True, null=True, upload_to='blog_large_image', verbose_name='Blog Large Image')),
                ('author', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, choices=[('Technology', 'technology'), ('Life Style', 'life_style'), ('Educational', 'educational'), ('Productivity', 'productivity')], max_length=250, null=True)),
                ('title', models.CharField(max_length=500)),
                ('excerpt', models.TextField(null=True)),
                ('body', models.TextField()),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('App', 'App'), ('Branding', 'Branding'), ('Development', 'Development'), ('Design', 'Design')], default='Tech News', max_length=31)),
                ('status', models.CharField(choices=[('Drafts', 'Draft'), ('Published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Career_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='Resume/CV')),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Contact_Ja',
            },
        ),
        migrations.CreateModel(
            name='Iconbox_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon-box', verbose_name='icon-box_ja')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Position_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=500, null=True)),
                ('team_image', models.ImageField(blank=True, default='/static/images/default_profile.jpg', null=True, upload_to='team_image', verbose_name='Profile Image')),
                ('quotes', models.TextField(blank=True, null=True)),
                ('social_media', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Workdetails_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeImage', models.ImageField(blank=True, null=True, upload_to='work_details/homeimage', verbose_name='home-image_ja')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_details/image', verbose_name='work_details_image')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.CharField(max_length=150)),
                ('awards', models.CharField(blank=True, max_length=150, null=True)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('largeImage', models.ImageField(blank=True, null=True, upload_to='work_details/largeimage', verbose_name='work_details_Large_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asha_web_ja.category_ja')),
            ],
            options={
                'verbose_name': 'WorkDetail_Ja',
                'verbose_name_plural': 'WorkDetails_Ja',
            },
        ),
        migrations.CreateModel(
            name='WorkImages_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=asha_web_ja.models.get_upload_to)),
                ('work', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asha_web_ja.workdetails_ja')),
            ],
            options={
                'verbose_name': 'Work Gallary Image Japanese',
                'verbose_name_plural': 'Work Gallary Images Japanese',
            },
        ),
        migrations.CreateModel(
            name='Vacancy_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('work_time', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-Time'), ('Remote', 'Remotely')], default='Full-Time', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('responsibilites', models.TextField()),
                ('description', models.TextField()),
                ('salary_range', models.CharField(max_length=150)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asha_web_ja.position_ja', verbose_name='Position_ja')),
            ],
        ),
    ]
