# Generated by Django 3.1.7 on 2021-05-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web_ja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_ja',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='career_ja',
            options={'verbose_name': 'Career', 'verbose_name_plural': 'Careers'},
        ),
        migrations.AlterModelOptions(
            name='category_ja',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact_ja',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='iconbox_ja',
            options={'verbose_name': 'Icon-box', 'verbose_name_plural': 'Icon-boxes'},
        ),
        migrations.AlterModelOptions(
            name='position_ja',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='vacancy_ja',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterModelOptions(
            name='workdetails_ja',
            options={'verbose_name': 'WorkDetail', 'verbose_name_plural': 'WorkDetails'},
        ),
        migrations.AddField(
            model_name='blog_ja',
            name='blog_en',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Blog EN ID'),
        ),
        migrations.AlterField(
            model_name='iconbox_ja',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon-box', verbose_name='icon-box'),
        ),
        migrations.AlterField(
            model_name='vacancy_ja',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asha_web_ja.position_ja', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='workdetails_ja',
            name='homeImage',
            field=models.ImageField(blank=True, null=True, upload_to='work_details/homeimage', verbose_name='home-image'),
        ),
    ]
