# Generated by Django 3.1.7 on 2021-06-23 10:31

import asha_web_ja.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web_ja', '0003_auto_20210514_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('drafts', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Notice_Ja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notice_details/image', verbose_name='notice_image')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hidden_date', models.DateTimeField(default=asha_web_ja.models.Notice_Ja.return_date_time)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pop_up', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Drafts', 'Draft'), ('Published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
        ),
    ]
