# Generated by Django 3.1.7 on 2021-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web_ja', '0004_faq_ja_notice_ja'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq_ja',
            name='Faq_en',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Faq EN ID'),
        ),
        migrations.AddField(
            model_name='notice_ja',
            name='notice_en',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Notice EN ID'),
        ),
    ]
