# Generated by Django 3.1.7 on 2021-06-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web_ja', '0005_auto_20210623_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_ja',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
