# Generated by Django 3.1.7 on 2021-04-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('designation', models.CharField(blank=True, max_length=500, null=True)),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='team_image')),
                ('quotes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
