# Generated by Django 3.1.7 on 2021-04-06 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Team'},
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_image', verbose_name='Profile Image'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_image', verbose_name='Blog Image')),
                ('blog_large_image', models.ImageField(blank=True, null=True, upload_to='blog_large_image', verbose_name='Blog Large Image')),
                ('author', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=500)),
                ('excerpt', models.TextField(null=True)),
                ('body', models.TextField()),
                ('tags', models.CharField(choices=[('app', 'App'), ('branding', 'Branding'), ('development', 'Development'), ('Design', 'App')], default='Tech News', max_length=50)),
                ('status', models.CharField(choices=[('drafts', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asha_web.category')),
            ],
            options={
                'verbose_name': ('Blog',),
                'verbose_name_plural': ('Blogs',),
                'ordering': ('-date',),
            },
            managers=[
                ('blogobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
