# Generated by Django 3.1.7 on 2021-04-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0002_auto_20210406_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='Resume/CV')),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterModelManagers(
            name='blog',
            managers=[
            ],
        ),
    ]
