# Generated by Django 3.1.7 on 2021-04-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0003_auto_20210407_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='phonenumber',
            field=models.IntegerField(max_length=14),
        ),
    ]
