# Generated by Django 3.1.7 on 2021-04-07 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0004_auto_20210407_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='career',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('work_time', models.CharField(choices=[('part-time', 'Part-Time'), ('full-time', 'Full-time'), ('Remote', 'Remotely')], default='Full-Time', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('responsibilites', models.TextField()),
                ('description', models.TextField()),
                ('salary_range', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asha_web.category', verbose_name='Category')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asha_web.position', verbose_name='Position')),
            ],
        ),
    ]
