# Generated by Django 3.1.7 on 2021-04-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0006_auto_20210407_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='social_media',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, default='/static/images/default_profile.jpg', null=True, upload_to='team_image', verbose_name='Profile Image'),
        ),
    ]
