# Generated by Django 3.1.7 on 2021-04-28 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0008_added_blog_career_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iconbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon-box', verbose_name='icon-box')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeImage', models.ImageField(blank=True, null=True, upload_to='work_details/homeimage', verbose_name='home-image')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_details/image', verbose_name='work_details_image')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.CharField(max_length=150)),
                ('awards', models.CharField(blank=True, max_length=150, null=True)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('largeImage', models.ImageField(blank=True, null=True, upload_to='work_details/largeimage', verbose_name='work_details_Large_image')),
                ('gallery', models.FileField(upload_to='work_details/gallery')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asha_web.category')),
            ],
            options={
                'verbose_name': 'WorkDetail',
                'verbose_name_plural': 'WorkDetails',
            },
        ),
    ]
