# Generated by Django 3.1.7 on 2021-04-30 09:10

import asha_web.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0009_iconbox_workdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetails',
            name='gallery',
        ),
        migrations.CreateModel(
            name='WorkImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=asha_web.models.get_upload_to)),
                ('work', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asha_web.workdetails')),
            ],
            options={
                'verbose_name': 'Work Gallary Image',
                'verbose_name_plural': 'Work Gallary Images',
            },
        ),
    ]
