# Generated by Django 3.1.7 on 2021-05-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0011_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='category',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Technology', 'technology'), ('Life Style', 'life_style'), ('Educational', 'educational'), ('Productivity', 'productivity')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Drafts', 'Draft'), ('Published', 'Published')], default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_time',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-Time'), ('Remote', 'Remotely')], default='Full-Time', max_length=200),
        ),
    ]
