# Generated by Django 3.1.7 on 2021-05-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0012_remove_category_foreign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='iconbox',
            options={'verbose_name': 'Icon-box', 'verbose_name_plural': 'Icon-boxes'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
