# Generated by Django 3.1.7 on 2021-06-01 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0014_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hidden_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notice',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('Drafts', 'Draft'), ('Published', 'Published')], default='published', max_length=10),
        ),
    ]
