# Generated by Django 3.1.7 on 2021-06-01 04:15

import asha_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0015_auto_20210601_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='hidden_date',
            field=models.DateTimeField(default=asha_web.models.Notice.return_date_time),
        ),
    ]
