# Generated by Django 3.1.7 on 2021-06-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0016_auto_20210601_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='pop_up',
            field=models.BooleanField(default=False),
        ),
    ]
