# Generated by Django 3.1.7 on 2021-06-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0014_faq'),
        ('asha_web', '0017_notice_pop_up'),
    ]

    operations = [
    ]
