# Generated by Django 3.1.7 on 2021-06-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0019_team_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='level',
        ),
    ]
