# Generated by Django 3.1.7 on 2021-06-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0020_remove_team_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
