# Generated by Django 3.1.7 on 2021-06-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asha_web', '0023_team_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
    ]
